title: Brian Bacik
logo: "/images/profile.png"
description: >
  Data Science | Machine Learning | AI
  <br>
  <br>
  10 years experience leveraging AI and ML across industries from biotech to public health to consumer goods
  <br>
  <br>
  Passionate about using AI to make the world better, and fascinated by the technological, ethical, and social implications of this incredible technology.
  <br>
  <br>
  
theme: jekyll-theme-minimal
