title: Brian Bacik
logo: "/images/profile.png"
description: >
  Data scientist at UTHealth trying to do some good in the world
  <br>
  <a href="https://www.linkedin.com/in/brian-bacik/">LinkedIn</a>
  
theme: jekyll-theme-minimal
